# Generated by Django 2.2 on 2019-04-23 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0002_auto_20190423_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pics',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='third_app.UserProfileInfo'),
        ),
    ]
